// constants/allProducts.ts

// Interface for a Product, to ensure type consistency
export interface Product {
  id: string; // Unique identifier for the product
  name: string;
  description: string;
  image: string; // URL to the product image
  discountPrice: number; // Current discounted price
  originalPrice: number; // Original price before discount
  rating: number; // Average rating (e.g., 4.5)
  review: number; // Number of reviews
  category: string; // Product category (e.g., "Laptops", "Smartphones")
  delivery: number; // Estimated delivery time in days
  brand?: string; // Optional: Brand of the product
  galleryImages?: string[]; // Optional: Array of additional image URLs
  warranty?: number; // Optional: Warranty in years
}

export const allProducts: Product[] = [
  {
    id: "prod_001",
    name: "Refurbished MacBook Air M1 (2020)",
    description: "Excellent condition, powerful M1 chip, 8GB RAM, 256GB SSD. Perfect for everyday tasks and light creative work.",
    image: "https://placehold.co/600x400/FFD700/000000?text=MacBook+Air",
    discountPrice: 89900.00,
    originalPrice: 105000.00,
    rating: 4.9,
    review: 350,
    category: "Laptops",
    delivery: 3,
    brand: "Apple",
    galleryImages: [
      "https://placehold.co/600x400/FFD700/000000?text=MacBook+Air+1",
      "https://placehold.co/600x400/FFD700/000000?text=MacBook+Air+2"
    ],
    warranty: 1,
  },
  {
    id: "prod_002",
    name: "Google Pixel 6 Pro (Unlocked)",
    description: "Grade A refurbished. Stunning camera, Tensor chip, 128GB storage. Minor cosmetic wear.",
    image: "https://placehold.co/600x400/5CB85C/FFFFFF?text=Pixel+6+Pro",
    discountPrice: 42500.00,
    originalPrice: 65000.00,
    rating: 4.7,
    review: 210,
    category: "Smartphones",
    delivery: 4,
    brand: "Google",
    warranty: 0.5,
  },
  {
    id: "prod_003",
    name: "Bose QuietComfort 35 II Headphones",
    description: "Immersive sound, world-class noise cancellation. Perfect for travel and focus. Very good condition.",
    image: "https://placehold.co/600x400/333333/FFFFFF?text=Bose+QC35",
    discountPrice: 15500.00,
    originalPrice: 22000.00,
    rating: 4.6,
    review: 480,
    category: "Audio",
    delivery: 2,
    brand: "Bose",
  },
  {
    id: "prod_004",
    name: "Gaming PC (Ryzen 5, RTX 3060)",
    description: "High-performance gaming PC. Fresh thermal paste, tested thoroughly. Ready for 1080p gaming.",
    image: "https://placehold.co/600x400/FF6347/FFFFFF?text=Gaming+PC",
    discountPrice: 78000.00,
    originalPrice: 110000.00,
    rating: 4.8,
    review: 95,
    category: "PC Components", // Changed to PC Components as it's a full PC
    delivery: 5,
    brand: "Custom Build",
  },
  {
    id: "prod_005",
    name: "Canon EOS 200D DSLR Camera",
    description: "Entry-level DSLR, great for beginners. Includes 18-55mm lens. Minor signs of use.",
    image: "https://placehold.co/600x400/F0F0F0/333333?text=Canon+200D",
    discountPrice: 32000.00,
    originalPrice: 45000.00,
    rating: 4.5,
    review: 150,
    category: "Cameras",
    delivery: 4,
    brand: "Canon",
  },
  {
    id: "prod_006",
    name: "Samsung Galaxy Tab S7 (LTE)",
    description: "Versatile Android tablet with S Pen support. Ideal for productivity and entertainment. Good condition.",
    image: "https://placehold.co/600x400/90EE90/000000?text=Galaxy+Tab+S7",
    discountPrice: 38000.00,
    originalPrice: 50000.00,
    rating: 4.6,
    review: 110,
    category: "Tablets",
    delivery: 3,
    brand: "Samsung",
  },
  {
    id: "prod_007",
    name: "Sony PlayStation 5 (Disc Edition)",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers and 3D Audio, and an all-new generation of incredible PlayStation® games.",
    image: "https://placehold.co/600x400/DFFF8F/333333?text=PS5",
    discountPrice: 45000.00,
    originalPrice: 55000.00,
    rating: 4.9,
    review: 500,
    category: "Gaming Consoles",
    delivery: 5,
    brand: "Sony",
  },
  {
    id: "prod_008",
    name: "Amazon Echo Dot (4th Gen)",
    description: "Smart speaker with Alexa. Control smart home devices, play music, and more. Used, but fully functional.",
    image: "https://placehold.co/600x400/E0E0E0/333333?text=Echo+Dot+4th+Gen",
    discountPrice: 2500.00,
    originalPrice: 4000.00,
    rating: 4.7,
    review: 280,
    category: "Smart Home",
    delivery: 2,
    brand: "Amazon",
  },
  {
    id: "prod_009",
    name: "Apple Watch Series 7 (GPS, 45mm)",
    description: "Large, always-on Retina display. Track your fitness, answer calls. Good condition.",
    image: "https://placehold.co/600x400/B0E0E6/000000?text=Apple+Watch+7",
    discountPrice: 28000.00,
    originalPrice: 35000.00,
    rating: 4.7,
    review: 190,
    category: "Accessories",
    delivery: 3,
    brand: "Apple",
  },
  {
    id: "prod_010",
    name: "Nvidia GeForce RTX 2060 GPU",
    description: "Entry-level ray tracing, great for 1080p gaming. Fully tested and cleaned.",
    image: "https://placehold.co/600x400/A9A9A9/FFFFFF?text=RTX+2060",
    discountPrice: 22000.00,
    originalPrice: 35000.00,
    rating: 4.4,
    review: 70,
    category: "PC Components",
    delivery: 3,
    brand: "Nvidia",
  },
  {
    id: "prod_011",
    name: "Dell XPS 13 (9300) Ultrabook",
    description: "Compact and powerful, 10th Gen i7, 16GB RAM, 512GB SSD. Minor scratches on lid.",
    image: "https://placehold.co/600x400/ADD8E6/000000?text=Dell+XPS+13",
    discountPrice: 75000.00,
    originalPrice: 95000.00,
    rating: 4.8,
    review: 180,
    category: "Laptops",
    delivery: 4,
    brand: "Dell",
  },
  {
    id: "prod_012",
    name: "Samsung Galaxy S21 Ultra 5G",
    description: "Flagship smartphone with amazing camera system and display. 256GB storage. Near mint condition.",
    image: "https://placehold.co/600x400/87CEEB/FFFFFF?text=Galaxy+S21+Ultra",
    discountPrice: 58000.00,
    originalPrice: 80000.00,
    rating: 4.7,
    review: 300,
    category: "Smartphones",
    delivery: 3,
    brand: "Samsung",
  },
  {
    id: "prod_013",
    name: "Sennheiser HD 599 SE Open-Back Headphones",
    description: "Audiophile-grade sound for music lovers. Excellent condition.",
    image: "https://placehold.co/600x400/6A5ACD/FFFFFF?text=Sennheiser+HD599",
    discountPrice: 12000.00,
    originalPrice: 18000.00,
    rating: 4.6,
    review: 90,
    category: "Audio",
    delivery: 2,
    brand: "Sennheiser",
  },
  {
    id: "prod_014",
    name: "Logitech G502 HERO Gaming Mouse",
    description: "High-performance wired gaming mouse with customizable weights. Very good condition.",
    image: "https://placehold.co/600x400/4682B4/FFFFFF?text=Logitech+G502",
    discountPrice: 3500.00,
    originalPrice: 5000.00,
    rating: 4.7,
    review: 220,
    category: "Accessories",
    delivery: 2,
    brand: "Logitech",
  },
  {
    id: "prod_015",
    name: "Nikon D3500 DSLR Camera",
    description: "Compact and easy-to-use DSLR. Ideal for beginners. Comes with kit lens.",
    image: "https://placehold.co/600x400/8B0000/FFFFFF?text=Nikon+D3500",
    discountPrice: 28000.00,
    originalPrice: 40000.00,
    rating: 4.4,
    review: 130,
    category: "Cameras",
    delivery: 4,
    brand: "Nikon",
  },
  {
    id: "prod_016",
    name: "Microsoft Surface Pro 7",
    description: "2-in-1 tablet/laptop. i5 processor, 8GB RAM, 128GB SSD. Some light scratches on back.",
    image: "https://placehold.co/600x400/BDB76B/000000?text=Surface+Pro+7",
    discountPrice: 60000.00,
    originalPrice: 85000.00,
    rating: 4.5,
    review: 100,
    category: "Tablets",
    delivery: 3,
    brand: "Microsoft",
  },
  {
    id: "prod_017",
    name: "Nintendo Switch V2",
    description: "Hybrid gaming console, play at home or on the go. Console only, no joy-cons.",
    image: "https://placehold.co/600x400/C0C0C0/333333?text=Nintendo+Switch",
    discountPrice: 20000.00,
    originalPrice: 28000.00,
    rating: 4.7,
    review: 310,
    category: "Gaming Consoles",
    delivery: 3,
    brand: "Nintendo",
  },
  {
    id: "prod_018",
    name: "Google Nest Hub (2nd Gen)",
    description: "Smart display with Google Assistant. Control smart devices, watch videos. Good condition.",
    image: "https://placehold.co/600x400/D3D3D3/000000?text=Nest+Hub+2nd+Gen",
    discountPrice: 5000.00,
    originalPrice: 7500.00,
    rating: 4.6,
    review: 160,
    category: "Smart Home",
    delivery: 2,
    brand: "Google",
  },
  {
    id: "prod_019",
    name: "HP Pavilion Gaming Laptop 15",
    description: "Budget gaming laptop with GTX 1650. Minor wear on keyboard, fully functional.",
    image: "https://placehold.co/600x400/ADD8E6/000000?text=HP+Gaming+15",
    discountPrice: 55000.00,
    originalPrice: 70000.00,
    rating: 4.2,
    review: 105,
    category: "Laptops",
    delivery: 4,
    brand: "HP",
  },
  {
    id: "prod_020",
    name: "OnePlus 9 Pro 5G",
    description: "Smooth display, fast charging, Hasselblad camera. 128GB, good condition.",
    image: "https://placehold.co/600x400/FFB6C1/000000?text=OnePlus+9+Pro",
    discountPrice: 40000.00,
    originalPrice: 60000.00,
    rating: 4.5,
    review: 180,
    category: "Smartphones",
    delivery: 3,
    brand: "OnePlus",
  },
  {
    id: "prod_021",
    name: "JBL Flip 5 Portable Speaker",
    description: "Compact and powerful waterproof Bluetooth speaker. Minor scuffs, great sound.",
    image: "https://placehold.co/600x400/FFA07A/000000?text=JBL+Flip+5",
    discountPrice: 5000.00,
    originalPrice: 7000.00,
    rating: 4.7,
    review: 250,
    category: "Audio",
    delivery: 2,
    brand: "JBL",
  },
  {
    id: "prod_022",
    name: "Corsair K70 RGB MK.2 Mechanical Keyboard",
    description: "Cherry MX Red switches, vibrant RGB lighting. Cleaned and tested.",
    image: "https://placehold.co/600x400/FFDAB9/000000?text=Corsair+K70",
    discountPrice: 8500.00,
    originalPrice: 12000.00,
    rating: 4.8,
    review: 140,
    category: "Accessories",
    delivery: 3,
    brand: "Corsair",
  },
  {
    id: "prod_023",
    name: "Sony Alpha a6000 Mirrorless Camera",
    description: "Fast autofocus, great image quality. Ideal for enthusiast photographers. Body only.",
    image: "https://placehold.co/600x400/F4A460/000000?text=Sony+a6000",
    discountPrice: 35000.00,
    originalPrice: 50000.00,
    rating: 4.6,
    review: 100,
    category: "Cameras",
    delivery: 4,
    brand: "Sony",
  },
  {
    id: "prod_024",
    name: "Xbox Series S Console",
    description: "All-digital next-gen gaming. Compact design, fast load times. Excellent condition.",
    image: "https://placehold.co/600x400/B0C4DE/000000?text=Xbox+Series+S",
    discountPrice: 24000.00,
    originalPrice: 32000.00,
    rating: 4.8,
    review: 280,
    category: "Gaming Consoles",
    delivery: 4,
    brand: "Microsoft",
  },
  {
    id: "prod_025",
    name: "Ring Video Doorbell 3 Plus",
    description: "Enhanced security for your home. Pre-roll video, removable battery. Fully functional.",
    image: "https://placehold.co/600x400/A2CD5A/000000?text=Ring+Doorbell",
    discountPrice: 12000.00,
    originalPrice: 18000.00,
    rating: 4.4,
    review: 75,
    category: "Smart Home",
    delivery: 3,
    brand: "Ring",
  },
  {
    id: "prod_026",
    name: "Acer Nitro 5 Gaming Laptop",
    description: "Affordable gaming power with GTX 1650. Well-maintained, good performance.",
    image: "https://placehold.co/600x400/FF6347/FFFFFF?text=Acer+Nitro+5",
    discountPrice: 52000.00,
    originalPrice: 68000.00,
    rating: 4.1,
    review: 90,
    category: "Laptops",
    delivery: 5,
    brand: "Acer",
  },
  {
    id: "prod_027",
    name: "Xiaomi Redmi Note 10 Pro",
    description: "Budget-friendly smartphone with 108MP camera. 128GB, minor screen scratches.",
    image: "https://placehold.co/600x400/E0BBE4/000000?text=Redmi+Note+10",
    discountPrice: 13000.00,
    originalPrice: 17000.00,
    rating: 4.3,
    review: 200,
    category: "Smartphones",
    delivery: 3,
    brand: "Xiaomi",
  },
  {
    id: "prod_028",
    name: "Audio-Technica ATH-M50x Headphones",
    description: "Industry-standard monitor headphones. Excellent for studio or casual listening.",
    image: "https://placehold.co/600x400/957DAD/FFFFFF?text=ATH-M50x",
    discountPrice: 9000.00,
    originalPrice: 13000.00,
    rating: 4.8,
    review: 300,
    category: "Audio",
    delivery: 2,
    brand: "Audio-Technica",
  },
  {
    id: "prod_029",
    name: "WD Black SN750 1TB NVMe SSD",
    description: "High-speed storage for gaming and productivity. Fully tested.",
    image: "https://placehold.co/600x400/624F82/FFFFFF?text=WD+Black+SSD",
    discountPrice: 6500.00,
    originalPrice: 10000.00,
    rating: 4.7,
    review: 60,
    category: "PC Components",
    delivery: 3,
    brand: "Western Digital",
  },
  {
    id: "prod_030",
    name: "GoPro HERO9 Black",
    description: "Capture stunning 5K video and 20MP photos. Waterproof, great for adventure.",
    image: "https://placehold.co/600x400/5B5F97/FFFFFF?text=GoPro+Hero9",
    discountPrice: 25000.00,
    originalPrice: 35000.00,
    rating: 4.5,
    review: 115,
    category: "Cameras",
    delivery: 4,
    brand: "GoPro",
  },
  {
    id: "prod_031",
    name: "Apple iPad Air 4 (2020)",
    description: "Powerful and versatile tablet. A14 Bionic chip, Liquid Retina display. Minor back scuffs.",
    image: "https://placehold.co/600x400/494D7E/FFFFFF?text=iPad+Air+4",
    discountPrice: 48000.00,
    originalPrice: 60000.00,
    rating: 4.8,
    review: 170,
    category: "Tablets",
    delivery: 3,
    brand: "Apple",
  },
  {
    id: "prod_032",
    name: "Valve Steam Deck (64GB)",
    description: "Handheld gaming PC, play your Steam library on the go. Very good condition.",
    image: "https://placehold.co/600x400/393E46/FFFFFF?text=Steam+Deck",
    discountPrice: 32000.00,
    originalPrice: 40000.00,
    rating: 4.9,
    review: 200,
    category: "Gaming Consoles",
    delivery: 5,
    brand: "Valve",
  },
  {
    id: "prod_033",
    name: "Philips Hue White and Color Ambiance Starter Kit",
    description: "Smart lighting kit with bridge and 3 bulbs. Create any mood. Fully functional.",
    image: "https://placehold.co/600x400/2C3E50/FFFFFF?text=Philips+Hue",
    discountPrice: 8000.00,
    originalPrice: 12000.00,
    rating: 4.6,
    review: 130,
    category: "Smart Home",
    delivery: 3,
    brand: "Philips",
  },
  {
    id: "prod_034",
    name: "Razer DeathAdder V2 Gaming Mouse",
    description: "Ergonomic wired gaming mouse with optical sensor. Good condition.",
    image: "https://placehold.co/600x400/1ABC9C/000000?text=Razer+DeathAdder",
    discountPrice: 4000.00,
    originalPrice: 6000.00,
    rating: 4.7,
    review: 190,
    category: "Accessories",
    delivery: 2,
    brand: "Razer",
  },
  {
    id: "prod_035",
    name: "Samsung SSD 860 Evo 500GB",
    description: "Reliable SATA SSD for faster boot times and app loading. Tested for health.",
    image: "https://placehold.co/600x400/2ECC71/000000?text=Samsung+SSD",
    discountPrice: 3500.00,
    originalPrice: 6000.00,
    rating: 4.6,
    review: 80,
    category: "PC Components",
    delivery: 3,
    brand: "Samsung",
  },
];
